
GET http://localhost:8080/posts

###

GET http://localhost:8080/posts/1

###

POST http://localhost:8080/posts
Content-Type: application/json

{
	"id": 3,
	"title": "test"
}

###

DELETE http://localhost:8080/posts/1
